### ISSUE TITLE
Store clamp values in link

### ISSUE THREAD

**Issue by Akiyamka** [codeAdrian/modern-fluid-typography-editor#2]
In would be cool if I can write right into style something like
```css
h1 {
  font-size: clamp(1rem, 2.5vw, 2rem);  /* Explainer: modern-fluid-typography.vercel.app/#/1/2.5/2 */
}
```
